trigger:
  branches:
    include:
    - master
    - Develop
  paths:
    include:
    - 'FourPatientApp-UI'

pr:
  branches:
    include:
    - master
    - Develop
  paths:
    include:
    - 'FourPatientApp-UI'

variables:
  appDir: 'FourPatientApp-UI'

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  displayName: node 14
  inputs:
    versionSpec: '14.x'

- script: npm ci
  displayName: npm install
  workingDirectory: $(appDir)

- script: npx ng build
  displayName: ng build
  workingDirectory: $(appDir)

- script: npx ng test --browsers ChromeHeadless --watch false --code-coverage || true
  displayName: ng test
  workingDirectory: $(appDir)
 