apiVersion: v1
kind: Service
metadata:
  name: fourpatient-frontend
  labels:
    app: fourpatient
    role: ui
spec:
  type: NodePort
  selector:
    app: 4patient
    role: ui
  ports:
  - port: 80
    nodePort: 30006

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fourpatient-frontend
  labels:
    app: fourpatient
    role: ui
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fourpatient
      role: ui
  template:
    metadata:
      labels:
        app: fourpatient
        role: ui
    spec:
      imagePullSecrets:
      - name: fourpatient-frontend
      containers:
      - name: ui
        image: fourpatient/frontend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 4200
