apiVersion: v1
kind: Service
metadata:
  name: fourpatient-webapi
  labels:
    app: symptomatic
    role: api
spec:
  type: NodePort
  selector:
    app: fourpatient
    role: ui
  ports:
  - port: 80
    nodePort: 30005

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fourpatient-webapi
  labels:
    app: fourpatient
    role: api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fourpatient
      role: api
  template:
    metadata:
      labels:
        app: fourpatient
        role: api
    spec:
      imagePullSecrets:
      - name: fourpatient-webapi
      containers:
      - name: api
        image: fourpatient/webapi:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 44391